load("//:monad.bzl", "monad_cc_library")

monad_cc_library(
    name = "core",
    srcs = ["assert.cpp"],
    hdrs = [
        "assert.h",
        "cases.hpp",
    ],
    visibility = ["//visibility:public"],
)
